services:
  vulcanexus:
    image: custom_vulcanexus
    hostname: DDS_host
    container_name: pcbinfo
    build: 
      context: .
      dockerfile: build/custom_vulcanexus/Dockerfile
    networks:
      - mynet
    privileged: true
    ipc: host
    command: sleep infinity
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
       - ./configs/ros2_pkgs/control_station_ws/src:/control_station_ws/src
       - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      # FastApi server for the pcb_images
      - 5001:5000


  mongo_db:
    image: mongo:4.4
    hostname: mongo_host
    container_name: mongo_db
    networks:
      - mynet
    privileged: true
    ipc: host
    command: --bind_ip_all
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  orion_ld:
    image: fiware/orion-ld:1.9.0
    hostname: orion_host
    container_name: orion
    networks:
      - mynet
    privileged: true
    ipc: host
    command: -dbhost mongo_db -logLevel DEBUG -wip dds -mongocOnly # -forwarding -experimental
    environment:
      - ORIONLD_MONGO_HOST=mongo_db
    volumes:
       - ./configs/contextbroker/config-dds.json:/root/.orionld
    depends_on:
      - mongo_db
    ports:
      - "1026:1026"
    restart: always
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 30s
      retries: 15



  crate_db:
    image: crate:latest
    hostname: crate_host
    container_name: crate_db
    networks:
      - mynet
    privileged: true
    ipc: host
    volumes:
      - crate_data:/data
    ports:
      - 4200:4200

  quantumleap:
    image: orchestracities/quantumleap
    hostname: ql_host
    container_name: quantumleap
    networks:
      - mynet
    privileged: true
    ipc: host  
    environment:
      - CRATE_HOST=crate_db
      - LOGLEVEL=DEBUG
    depends_on:
      - crate_db
    ports:
      - 8668:8668
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1
      
  grafana:
    image: grafana/grafana
    hostname: grafana_host
    container_name: grafana
    networks:
      - mynet
    privileged: true
    ipc: host
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 443:3000
    


volumes:
  mongo_data:
  grafana-storage:
  crate_data:


networks:
  mynet:
    driver: bridge     

    