services:
  vulcanexus:
    image: custom_vulcanexus
    hostname: DDS_host
    container_name: pcbinfo
    build: 
      context: .
      dockerfile: build/custom_vulcanexus/Dockerfile
    networks:
      - mynet
    privileged: true
    ipc: host
    command: sleep infinity
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
       - ./configs/ros2_pkgs/control_station_ws/src:/control_station_ws/src
       - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      # FastApi server for the pcb_images
      - 5000:5000


  mongo_db:
    image: mongo:4.4
    hostname: mongo_host
    container_name: mongo_db
    networks:
      - mynet
    privileged: true
    ipc: host
    command: --bind_ip_all
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  orion_ld:
    image: fiware/orion-ld:1.9.0
    hostname: orion_host
    container_name: orion
    networks:
      - mynet
    privileged: true
    ipc: host
    command: -dbhost mongo_db -logLevel DEBUG -wip dds -mongocOnly # -forwarding -experimental
    environment:
      - ORIONLD_MONGO_HOST=mongo_db
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_HOST=timescale
      - ORIONLD_TROE_PORT=5432
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
    volumes:
       - ./configs/contextbroker/config-ddsv2.json:/root/.orionld
    depends_on:
      - mongo_db
    ports:
      - 1026:1026
    restart: always
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 30s
      retries: 15



  timescale:
    image: timescale/timescaledb-ha:pg17-ts2.18
    hostname: timescale_host
    container_name: timescale
    networks:
      - mynet
    privileged: true
    ipc: host
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432  
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
  
  mintaka:
    image: fiware/mintaka:0.6.18
    hostname: mintaka_host
    container_name: mintaka
    networks:
      - mynet 
    privileged: true
    ipc: host
    environment:
      - MICRONAUT_SERVER_PORT=8080
      - MICRONAUT_METRICS_ENABLED=true
      - ENDPOINTS_ALL_PORT=8080
      - ENDPOINTS_METRICS_ENABLED=true
      - ENDPOINTS_HEALTH_ENABLED=true
      - DATASOURCES_DEFAULT_HOST=timescale
      - DATASOURCES_DEFAULT_PORT=5432
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABASE=orion
      - LOGGERS_LEVEL_ROOT=TRACE
    ports:
      - 8080:8080
    restart: always


  grafana:
    image: grafana/grafana
    hostname: grafana_host
    container_name: grafana
    networks:
      - mynet
    privileged: true
    ipc: host
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
    volumes:
      - ./configs/grafanadashboard/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./configs/grafanadashboard/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafanadashboard/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    ports:
      - 443:3000
    

  iot_agent_robot:
    image: iotagent-opcua
    hostname: iotagent_host
    container_name: iotagent_robot
    build: 
      context: .
      dockerfile: build/iotagent-opcua/Dockerfile
    networks:
      - mynet
    privileged: true
    ipc: host
    environment:
      - "CONFIGURATION_TYPE=static"
      - "CONFIG_RETRIEVAL=false"
      - "DEFAULT_KEY=iot"
      - "DEFAULT_TRANSPORT=OPCUA"
      - "IOTA_LOGLEVEL=DEBUG"
      - "IOTA_TIMESTAMP=true"
      - "IOTA_CB_HOST=orion_ld"
      - "IOTA_CB_PORT=1026"
      - "IOTA_CB_NGSIVERSION=ld"
      - "IOTA_CB_NGSILDCONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
      - "IOTA_CB_SERVICE=opcua_myur5e"
      - "IOTA_CB_SUBSERVICE=/mydemo"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongo_host"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent_opcua_myrobot"

      - "IOTA_SERVICE=opcua_myur5e"
      - "IOTA_SUBSERVICE=/mydemo"
      - "IOTA_PROVIDER_URL=http://iot_agent_robot:4041"
      - "IOTA_DEVICEREGDURATION=P20Y"
      - "IOTA_DEFAULTTYPE=Device"
      - "IOTA_DEFAULTRESOURCE=/iot/opcua"
      - "IOTA_EXPLICITATTRS=true"
      - "IOTA_EXTENDED_FORBIDDEN_CHARACTERS=[]"
      - "IOTA_AUTOPROVISION=true"
      - "IOTA_EXPRESS_LIMIT=50mb"

      - "IOTA_OPCUA_ENDPOINT=opc.tcp://host.docker.internal:4840"
      - "IOTA_OPCUA_SECURITY_MODE=None"
      - "IOTA_OPCUA_SECURITY_POLICY=None"
      #- "IOTA_OPCUA_SECURITY_USERNAME=null"
      #- "IOTA_OPCUA_SECURITY_PASSWORD=null"
      - "IOTA_OPCUA_UNIQUE_SUBSCRIPTION=false"
      - "IOTA_OPCUA_SUBSCRIPTION_NOTIFICATIONS_PER_PUBLISH=1000"
      - "IOTA_OPCUA_SUBSCRIPTION_PUBLISHING_ENABLED=true"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_LIFETIME_COUNT=100"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_MAX_KEEP_ALIVE_COUNT=10"
      - "IOTA_OPCUA_SUBSCRIPTION_REQ_PUBLISHING_INTERVAL=1000"
      - "IOTA_OPCUA_SUBSCRIPTION_PRIORITY=128"

      - "IOTA_OPCUA_MT_POLLING=false"
      - "IOTA_OPCUA_MT_AGENT_ID=agee01_"
      - "IOTA_OPCUA_MT_ENTITY_ID=agee01_mos"
      - "IOTA_OPCUA_MT_ENTITY_TYPE=Device"
      - "IOTA_OPCUA_MT_NAMESPACE_IGNORE=7"
      - "IOTA_OPCUA_MT_STORE_OUTPUT=true" 
      # default was true
    
    volumes:
        - ./configs/iotagent-opcua/config-ld-ur5e.js:/opt/iotagent-opcua/conf/config.js:ro
    depends_on:
      - mongo_db
      - orion_ld
    ports:
      - 4041:4041
      - 9229:9229
    extra_hosts:
      - "host.docker.internal:host-gateway"






volumes:
  mongo_data:
  grafana-storage:



networks:
  mynet:
    driver: bridge     

    